<?php


declare(strict_types=1);


namespace Easy\Command;

use Hyperf\Command\Annotation\Command;
use Easy\EasyCommand;

/**
 * Class EasyCMF.
 */
#[Command]
class EasyCMF extends EasyCommand
{
    protected ?string $name = 'easy';

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Handle the current command.
     */
    public function handle()
    {
        $result = shell_exec('php ' . BASE_PATH . '/bin/hyperf.php | grep easy');
        $this->line($this->getInfo(), 'comment');
        $this->line(preg_replace('/\s+Easy\s+/', '', $result), 'info');
    }
}
